-- File: Datapath.vhd
-- Generated by MyHDL 0.11.51
-- Date:    Sun Mar  8 20:37:49 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity Datapath is
    port (
        clk: in std_logic;
        reset: in std_logic;
        ext_const_i32_1_c_15: in unsigned(15 downto 0);
        ext_const_i32_2_c_14: in unsigned(15 downto 0);
        ext_const_i32_5_c_13: in unsigned(15 downto 0);
        ext_phi_01_0: in unsigned(15 downto 0);
        ext_phi_0_1: in unsigned(15 downto 0);
        out_arith_addi_0_1_8: out unsigned(15 downto 0);
        out_arith_muli_id4_id6_7: out unsigned(15 downto 0)
    );
end entity Datapath;


architecture MyHDL of Datapath is


type t_enum_t_state_1 is (
	STATE_0,
	STATE_1,
	STATE_2,
	STATE_3
	);
attribute enum_encoding of t_enum_t_state_1: type is "0001 0010 0100 1000";

signal zero: unsigned(15 downto 0);
signal state: t_enum_t_state_1;
signal cycle_sel: unsigned(1 downto 0);
signal iter_count: unsigned(1 downto 0);
signal done: std_logic;
signal enable_gen0_enable: std_logic;
signal enable_gen1_enable: std_logic;
signal enable_gen2_enable: std_logic;
signal enable_gen3_enable: std_logic;
signal enable_gen4_enable: std_logic;
signal enable_gen5_enable: std_logic;
signal additionneur0_a: unsigned(15 downto 0);
signal additionneur0_b: unsigned(15 downto 0);
signal additionneur0_s: unsigned(15 downto 0);
signal mux40_a2: unsigned(15 downto 0);
signal mux41_a1: unsigned(15 downto 0);
signal registre_enable1_sortie: unsigned(15 downto 0);
signal registre_enable2_sortie: unsigned(15 downto 0);
signal multiplicateur0_a: unsigned(15 downto 0);
signal multiplicateur0_b: unsigned(15 downto 0);
signal multiplicateur0_s: unsigned(15 downto 0);

begin


zero <= to_unsigned(0, 16);


fsm0_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            done <= '0';
            iter_count <= to_unsigned(0, 2);
            state <= STATE_0;
        else
            if (done = '1') then
                null;
            elsif (state = STATE_0) then
                state <= STATE_1;
            elsif (state = STATE_1) then
                state <= STATE_2;
            elsif (state = STATE_2) then
                state <= STATE_3;
            elsif (state = STATE_3) then
                if (signed(resize(iter_count, 3)) = (4 - 1)) then
                    done <= '1';
                else
                    iter_count <= (iter_count + 1);
                    state <= STATE_0;
                end if;
            end if;
        end if;
    end if;
end process fsm0_logic;

cycle_sel_gen0_logic: process (state) is
begin
    case state is
        when STATE_0 =>
            cycle_sel <= to_unsigned(0, 2);
        when STATE_1 =>
            cycle_sel <= to_unsigned(1, 2);
        when STATE_2 =>
            cycle_sel <= to_unsigned(2, 2);
        when others => -- STATE_3
            cycle_sel <= to_unsigned(3, 2);
    end case;
end process cycle_sel_gen0_logic;

enable_gen0_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_0)) then
        enable_gen0_enable <= '1';
    else
        enable_gen0_enable <= '0';
    end if;
end process enable_gen0_logic;

enable_gen1_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_0)) then
        enable_gen1_enable <= '1';
    else
        enable_gen1_enable <= '0';
    end if;
end process enable_gen1_logic;

enable_gen2_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_1)) then
        enable_gen2_enable <= '1';
    else
        enable_gen2_enable <= '0';
    end if;
end process enable_gen2_logic;

enable_gen3_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_1)) then
        enable_gen3_enable <= '1';
    else
        enable_gen3_enable <= '0';
    end if;
end process enable_gen3_logic;

enable_gen4_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_2)) then
        enable_gen4_enable <= '1';
    else
        enable_gen4_enable <= '0';
    end if;
end process enable_gen4_logic;

enable_gen5_logic: process (done, state) is
begin
    if ((done = '0') and (state = STATE_3)) then
        enable_gen5_enable <= '1';
    else
        enable_gen5_enable <= '0';
    end if;
end process enable_gen5_logic;


additionneur0_s <= (additionneur0_a + additionneur0_b);

mux40_comb: process (mux40_a2, zero, cycle_sel, ext_phi_0_1, ext_phi_01_0) is
begin
    case cycle_sel is
        when "00" =>
            additionneur0_a <= ext_phi_0_1;
        when "01" =>
            additionneur0_a <= ext_phi_01_0;
        when "10" =>
            additionneur0_a <= mux40_a2;
        when others =>
            additionneur0_a <= zero;
    end case;
end process mux40_comb;

mux41_comb: process (ext_const_i32_5_c_13, zero, cycle_sel, ext_const_i32_1_c_15, mux41_a1) is
begin
    case cycle_sel is
        when "00" =>
            additionneur0_b <= ext_const_i32_1_c_15;
        when "01" =>
            additionneur0_b <= mux41_a1;
        when "10" =>
            additionneur0_b <= ext_const_i32_5_c_13;
        when others =>
            additionneur0_b <= zero;
    end case;
end process mux41_comb;

registre_enable0_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            out_arith_addi_0_1_8 <= to_unsigned(0, 16);
        else
            if bool(enable_gen0_enable) then
                out_arith_addi_0_1_8 <= additionneur0_s;
            end if;
        end if;
    end if;
end process registre_enable0_logic;

registre_enable1_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            registre_enable1_sortie <= to_unsigned(0, 16);
        else
            if bool(enable_gen2_enable) then
                registre_enable1_sortie <= additionneur0_s;
            end if;
        end if;
    end if;
end process registre_enable1_logic;

registre_enable2_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            registre_enable2_sortie <= to_unsigned(0, 16);
        else
            if bool(enable_gen4_enable) then
                registre_enable2_sortie <= additionneur0_s;
            end if;
        end if;
    end if;
end process registre_enable2_logic;


multiplicateur0_s <= resize(multiplicateur0_a * multiplicateur0_b, 16);

mux42_comb: process (zero, registre_enable1_sortie, cycle_sel, ext_const_i32_5_c_13, ext_phi_0_1) is
begin
    case cycle_sel is
        when "00" =>
            multiplicateur0_a <= ext_const_i32_5_c_13;
        when "01" =>
            multiplicateur0_a <= ext_phi_0_1;
        when "10" =>
            multiplicateur0_a <= zero;
        when others =>
            multiplicateur0_a <= registre_enable1_sortie;
    end case;
end process mux42_comb;

mux43_comb: process (zero, registre_enable2_sortie, cycle_sel, ext_phi_0_1, ext_const_i32_2_c_14) is
begin
    case cycle_sel is
        when "00" =>
            multiplicateur0_b <= ext_phi_0_1;
        when "01" =>
            multiplicateur0_b <= ext_const_i32_2_c_14;
        when "10" =>
            multiplicateur0_b <= zero;
        when others =>
            multiplicateur0_b <= registre_enable2_sortie;
    end case;
end process mux43_comb;

registre_enable3_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            mux41_a1 <= to_unsigned(0, 16);
        else
            if bool(enable_gen1_enable) then
                mux41_a1 <= multiplicateur0_s;
            end if;
        end if;
    end if;
end process registre_enable3_logic;

registre_enable4_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            mux40_a2 <= to_unsigned(0, 16);
        else
            if bool(enable_gen3_enable) then
                mux40_a2 <= multiplicateur0_s;
            end if;
        end if;
    end if;
end process registre_enable4_logic;

registre_enable5_logic: process (clk) is
begin
    if rising_edge(clk) then
        if (reset = '1') then
            out_arith_muli_id4_id6_7 <= to_unsigned(0, 16);
        else
            if bool(enable_gen5_enable) then
                out_arith_muli_id4_id6_7 <= multiplicateur0_s;
            end if;
        end if;
    end if;
end process registre_enable5_logic;

end architecture MyHDL;
